# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRij2FFteEr2cO0J9YyOLX2-WRiFIhyE
"""

from google.colab import drive
drive.mount('/content/drive')

# =========================================================
# INSTALL STREAMLIT LIBRARIES
# =========================================================
pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# # =========================================================
# # STREAMLIT APP
# # =========================================================
# 
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # =========================================================
# # LOAD DATA
# # =========================================================
# df = pd.read_json(
#     "expert_knowledge_base.json",
#     encoding="latin1"
# )
# 
# # =========================================================
# # CPU / GPU TIERS
# # =========================================================
# CPU_TIER = {
#     "Intel Core Ultra 9 275HX": 5,
#     "AMD Ryzen 9 8945HS": 5,
#     "AMD Ryzen AI 9 HX 370": 5,
#     "Intel Core Ultra 7 266V": 4,
#     "Intel Core Ultra 7 258V": 4,
#     "Intel Core Ultra 7 155H": 4,
#     "Intel Core i7-13620H": 4,
#     "Intel Core i7-12650H ": 4,
#     "AMD Ryzen 7 8840HS": 4,
#     "AMD Ryzen 7 7840HS": 4,
#     "AMD Ryzen AI 7 350": 4,
#     "AMD Ryzen 7 250": 4,
#     "Qualcomm Snapdragon X Elite X1E-80-100": 4,
#     "Apple M5": 4,
#     "Apple M4": 4,
#     "Intel Core Ultra 5 225H": 3,
#     "Intel Core 5 120U": 3,
#     "Intel Core i5-12500H": 3,
#     "Intel Core i5-12450H": 3,
#     "Intel Core i5-1235U": 3,
#     "Intel Core i5-1334U": 3,
#     "Intel i7-1355U": 3,
#     "AMD Ryzen 7 8840U": 3,
#     "AMD Ryzen 7 7730U": 3,
#     "AMD Ryzen 7 5800U": 3,
#     "AMD Ryzen 5 7535HS": 3,
#     "AMD Ryzen 5 7530U": 3,
#     "AMD Ryzen 5 5600H": 3,
#     "Snapdragon X Plus (10-Core)": 3,
#     "Snapdragon X X1-26-100": 3,
#     "Apple A18 Pro": 2,
#     "Intel Celeron N4500": 1
# }
# 
# GPU_TIER = {
#     "NVIDIA GeForce RTX 5070 Ti": 4,
#     "NVIDIA GeForce RTX 5070": 4,
#     "NVIDIA GeForce RTX 4060": 4,
#     "NVIDIA GeForce RTX 4050": 3,
#     "NVIDIA RTX 3050 Ti": 3,
#     "NVIDIA GeForce RTX 3050": 3,
#     "NVIDIA GeForce RTX 2050": 3,
#     "10-core GPU": 3,
#     "8-core GPU": 3,
#     "Intel Arc Graphics 140V": 3,
#     "Intel Arc 130T": 3,
#     "Intel Arc Graphics": 3,
#     "Intel ARC Integrated Graphics": 3,
#     "AMD Radeon 780M": 3,
#     "AMD Radeon 780M Graphics": 3,
#     "AMD Radeon Graphics": 2,
#     "Intel Graphics": 2,
#     "Qualcomm Adreno Graphics": 2,
#     "5-core GPU": 2,
#     "Intel UHD Graphics": 1,
# }
# 
# # =========================================================
# # PRIORITY SCORES
# # =========================================================
# PORTABILITY_SCORE = {
#     "Ultra-Light (Highly Portable)": 1.0,
#     "Standard Weight": 0.6,
#     "Heavy (Desktop Replacement)": 0.2
# }
# 
# BATTERY_SCORE = {
#     "Excellent Battery (70Wh+)": 1.0,
#     "Good Battery (50-70Wh)": 0.7,
#     "Standard Battery (<50Wh)": 0.4
# }
# 
# SCREEN_SCORE = {
#     "Large (>=15.6\")": 1.0,
#     "Standard (14\")": 0.7,
#     "Compact (<=13.6\")": 0.5
# }
# 
# # =========================================================
# # CORE FUNCTIONS
# # =========================================================
# 
# def get_dynamic_weights(user_category):
#     c = user_category.lower()
# 
#     if "gaming" in c or "content creator" in c:
#         return {"cpu": 0.35, "gpu": 0.40, "ram": 0.15, "storage": 0.10}
# 
#     elif "programming/coding" in c:
#         return {"cpu": 0.40, "ram": 0.40, "gpu": 0.05, "storage": 0.15}
# 
#     elif "office/professional" in c or "casual/home user" in c or "student" in c:
#         return {"cpu": 0.40, "ram": 0.30, "gpu": 0.15, "storage": 0.15}
# 
#     return {"cpu": 0.40, "ram": 0.30, "gpu": 0.15, "storage": 0.15}
# 
# 
# def generate_justifications(laptop, cpu_tier, gpu_tier):
# 
#     reasons = []
# 
#     # RAM
#     ram = laptop["RAM (GB)"]
#     if ram >= 32:
#         reasons.append(f"Elite Memory Tier: Massive {ram}GB RAM offers complete future-proofing for heavy multitasking.")
#     elif ram == 16:
#         reasons.append(f"Sweet Spot Memory: Standard {ram}GB RAM provides smooth multitasking for daily use.")
#     else:
#         reasons.append(f"Baseline Memory: Budget-friendly {ram}GB RAM covers basic student tasks and browsing perfectly fine.")
# 
#     # CPU
#     if cpu_tier == 5:
#         reasons.append(f"Ultimate Powerhouse: {laptop['CPU']} delivers extreme performance for heavy workloads.")
#     elif cpu_tier == 4:
#         reasons.append(f"High-End Performance: {laptop['CPU']} handles demanding tasks smoothly.")
#     elif cpu_tier == 3:
#         reasons.append(f"Mainstream Reliability: {laptop['CPU']} is solid for everyday productivity.")
#     else:
#         reasons.append(f"Entry-Level Efficiency: {laptop['CPU']} is optimized for light usage.")
# 
#     # GPU
#     if gpu_tier == 4:
#         reasons.append(f"Elite Graphics: {laptop['GPU']} is perfect for gaming and creative work.")
#     elif gpu_tier == 3:
#         reasons.append(f"Capable Graphics: {laptop['GPU']} supports light gaming and editing.")
#     else:
#         reasons.append(f"Integrated Graphics: {laptop['GPU']} is efficient for daily tasks.")
# 
#     # STORAGE
#     storage = laptop["Storage (GB SSD)"]
#     if storage >= 1000:
#         reasons.append(f"Generous Storage Tier: {storage}GB SSD gives plenty of space for files and software.")
#     elif storage == 512:
#         reasons.append(f"Standard Storage Tier: {storage}GB SSD is balanced for student use.")
#     else:
#         reasons.append(f"Entry Storage Tier: {storage}GB SSD is sufficient for essential apps.")
# 
#     return reasons
# 
# def calculate_priority_boost(laptop, priorities):
# 
#     boost_score = 0
#     preference_reasons = []
# 
#     for index, priority in enumerate(priorities):
# 
#         rank = index + 1
#         multiplier = 4 - rank
# 
#         if priority.lower() == "weight":
# 
#             category = laptop.get("portability_category", "")
#             value = PORTABILITY_SCORE.get(category, 0.5)
# 
#             boost_score += (value * 0.15) * multiplier
# 
#             if rank == 1 and value == 1.0:
#                 preference_reasons.append(
#                     f"Top Priority Match: Ultra-light build ({laptop['Weight (kg)']}kg) supports maximum portability."
#                 )
# 
#         elif priority.lower() == "battery":
# 
#             category = laptop.get("battery_category", "")
#             value = BATTERY_SCORE.get(category, 0.4)
# 
#             boost_score += (value * 0.15) * multiplier
# 
#             if rank == 1 and value == 1.0:
#                 preference_reasons.append(
#                     f"Top Priority Match: {laptop['Battery Capacity (WHrs)']}WHrs battery supports all-day usage."
#                 )
# 
#         elif priority.lower() == "display":
# 
#             category = laptop.get("screen_category", "")
#             value = SCREEN_SCORE.get(category, 0.5)
# 
#             boost_score += (value * 0.15) * multiplier
# 
#             if rank == 1 and value == 1.0:
#                 preference_reasons.append(
#                     "Top Priority Match: Large display enhances productivity and content consumption."
#                 )
# 
#     return boost_score, preference_reasons
# 
# def score_laptop(laptop, user):
# 
#     # OS FILTER
#     if user["preferred_os"] != "Any":
#         if user["preferred_os"].lower() not in laptop["Operating System"].lower():
#             return -1, []
# 
#     # Budget filter
#     if laptop["Price (RM)"] > user["budget"]:
#         return -1, []
# 
#     weights = get_dynamic_weights(user["purpose"])
# 
#     cpu_tier = CPU_TIER.get(laptop["CPU"].strip(), 2)
#     gpu_tier = GPU_TIER.get(laptop["GPU"].strip(), 2)
# 
#     score = (
#         (laptop["RAM (GB)"] / 32) * weights["ram"] +
#         (cpu_tier / 5) * weights["cpu"] +
#         (gpu_tier / 4) * weights["gpu"] +
#         (laptop["Storage (GB SSD)"] / 2000) * weights["storage"]
#     )
# 
#     priority_boost, pref_reasons = calculate_priority_boost(
#     laptop,
#     user["priorities"]
#     )
# 
#     score += priority_boost
# 
#     justifications = pref_reasons + generate_justifications(
#     laptop,
#     cpu_tier,
#     gpu_tier
#     )
# 
#     if laptop["Category"].lower() == user["purpose"].lower():
#         score += 0.15
#         justifications.append(f"Targeted Fit: This device is design  '{laptop['Category']}' usage.")
# 
#     # ========================================================
#     # NORMALIZATION: Scale the final score between 0.0 and 1.0
#     # ========================================================
#     max_theoretical_score = 2.05
#     score = score / max_theoretical_score
# 
#     return round(score , 3), justifications
# 
# 
# def recommend(df, user):
# 
#     results = []
# 
#     for _, row in df.iterrows():
#         score, reasons = score_laptop(row, user)
# 
#         if score > 0:
#             results.append({
#                 "brand": row["Brand"],
#                 "model": row["Model Name"],
#                 "price": row["Price (RM)"],
#                 "cpu": row["CPU"],
#                 "gpu": row["GPU"],
#                 "ram": row["RAM (GB)"],
#                 "storage": row["Storage (GB SSD)"],
#                 "weight": row["Weight (kg)"],
#                 "os": row["Operating System"],
#                 "battery": row["Battery Capacity (WHrs)"],
#                 "score": score,
#                 "reasons": reasons
#             })
# 
#     # SORT BY SCORE
#     return sorted(results, key=lambda x: x["score"], reverse=True)
# 
# # =========================================================
# # STREAMLIT UI
# # =========================================================
# 
# st.set_page_config(page_title="Laptop Recommender", layout="wide")
# st.title("Laptop Recommendation System")
# 
# budget = st.sidebar.number_input(
#     "Budget (RM)",
#     min_value=1000,
#     max_value=50000,
#     value=5000,
#     step=100
# )
# 
# purpose = st.sidebar.selectbox(
#     "Purpose",
#     ["Student", "Gaming", "Programming/Coding", "Content Creator", "Office/Professional" , "Casual/Home User"]
# )
# os_choice = st.sidebar.selectbox("OS", ["Windows", "macOS", "Any"])
# 
# p1 = st.sidebar.selectbox("1st Priority", ["Weight", "Battery", "Display"])
# p2 = st.sidebar.selectbox("2nd Priority", ["Weight", "Battery", "Display"])
# p3 = st.sidebar.selectbox("3rd Priority", ["Weight", "Battery", "Display"])
# 
# user = {
#     "budget": budget,
#     "purpose": purpose,
#     "preferred_os": os_choice,
#     "priorities": [p1, p2, p3]
# }
# 
# # =========================================================
# # OUTPUT
# # =========================================================
# 
# if st.button("Get Recommendations"):
# 
#     results = recommend(df, user)
# 
#     if not results:
#         st.error("No laptops found.")
#     else:
#         st.success("Top Recommendations")
# 
#         for i, laptop in enumerate(results[:3], 1):
# 
#             st.markdown(f"## Option {i}: {laptop['brand']} {laptop['model']}")
# 
#             # Score
#             st.write(f"★ Match Score: {laptop['score']}")
# 
#             # Specs Summary
#             st.write("### Specifications Summary")
# 
#             col1, col2, col3 = st.columns(3)
# 
#             with col1:
#                 st.write(f"**Price:** RM {laptop['price']}")
#                 st.write(f"**CPU:** {laptop['cpu']}")
#                 st.write(f"**GPU:** {laptop['gpu']}")
# 
#             with col2:
#                 st.write(f"**RAM:** {laptop['ram']} GB")
#                 st.write(f"**Storage:** {laptop['storage']} GB")
#                 st.write(f"**Weight:** {laptop['weight']} kg")
# 
#             with col3:
#                 st.write(f"**Battery:** {laptop['battery']} WHrs")
#                 st.write(f"**OS:** {laptop['os']}")
# 
#             # Justifications
#             st.write("### Justifications")
#             for r in laptop["reasons"]:
#                 st.write("✔", r)
# 
#             st.markdown("---")

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

# =========================================================
# RUN STREAMLIT
# =========================================================

!streamlit run app.py &>/content/logs.txt &

# =========================================================
# CREATE PUBLIC WEBSITE LINK
# =========================================================

!./cloudflared tunnel --url http://localhost:8501
